#!/bin/bash
#
# Compilation Script for CrysFML library
# Author: Javier Gonzalez-Platas
# Date: July-2015
# Linux version
#
# Checking CrySFML Environment Variable
#
if [ -z "$CRYSFML" ]; then
   echo "****"
   echo "**** Please, set the environment variable CRYSFML in your .bashrc"
   echo "****"
   exit
fi
#
# Calling Program
#
if [ -z "$1" ]; then
cat << !
make_crysfml  : Make the CrysFML Library using Fortran Compilers
Syntax        : make_crysfml f95:g95:gfortran:ifort [m32|m64] [winter] [debug]
!
exit
fi
#
# Default values for Arguments
#
COMP=""
ARCH="m64"
DEBUG="N"
WINT="N"
#
# Arguments
#
for arg in "$@"
do
   case "$arg" in
      "f95")
         COMP=$arg
         ;;
      "g95")
         COMP=$arg
         ;;
      "gfortran")
         COMP=$arg
         ;;
      "ifort")
         COMP=$arg
         ;;
      "m32")
         ARCH=$arg
         ;;
      "m64")
         ARCH=$arg
         ;;
      "deb"*)
         DEBUG="Y"
         ;;
      "win"*)
         WINT="Y"
         ;;
   esac
done
#
# Check Compiler name
#
if [ -z $COMP ]; then
   echo "****"
   echo "**** Compiler name is wrong!!!. Please check it!"
   echo "****"
   exit
fi
#
# Detect if Directories exists
#
case "$COMP" in
   "f95")
        IDIR="Absoft"
        ;;
   "g95")
        IDIR="G95"
        ;;
   "gfortran")
        IDIR="GFortran"
        if [ "$ARCH" == "m64" ]; then
           IDIR="GFortran64"
        fi
        ;;
   "ifort")
        IDIR="ifort"
        if [ "$ARCH" == "m64" ]; then
           IDIR="ifort64"
        fi
        ;;
esac
if [ -d "$CRYSFML/$IDIR" ]; then
   if [ -d "$CRYSFML/$IDIR/LibC" ]; then
      echo " "
   else
      mkdir "$CRYSFML/$IDIR/LibC"
      mkdir "$CRYSFML/$IDIR/LibW"
   fi
else
   mkdir "$CRYSFML/$IDIR"
   mkdir "$CRYSFML/$IDIR/LibC"
   mkdir "$CRYSFML/$IDIR/LibW"
fi
#
# Compilation Options
#
if [ $DEBUG == "Y" ]; then
   case "$COMP" in
      "f95")
          OPT1="-c -g -O0"
          OPT2="-c -g -O0"
          ;;
      "g95")
          OPT1="-c -g -Wall"
          OPT2="-c -g -Wall"
          ;;
      "gfortran")
          OPT1="-c -g -fbacktrace -ffree-line-length-none"
          OPT2="-c -g -fbacktrace -ffree-line-length-none"
          ;;
      "ifort")
          OPT1="-c -g -warn -$ARCH"
          OPT2="-c -g -warn -$ARCH"
          ;;
   esac
else
   case "$COMP" in
      "f95")
          OPT1="-c -O2 -N11"
          OPT2="-c -O0 -N11"
          ;;
      "g95")
          OPT1="-c -O"
          OPT2="-c -O0"
          ;;
      "gfortran")
          OPT1="-c -O -ffree-line-length-none -funroll-loops"
          OPT2="-c -O0 -ffree-line-length-none -funroll-loops"
          ;;
      "ifort")
          #OPT1="-c -O -warn -$ARCH -Qvec-report0"
          #OPT2="-c -O0 -warn -$ARCH -Qvec-report0"
          OPT1="-c -O -warn -$ARCH -Qopt-report:0"
          OPT2="-c -O0 -warn -$ARCH -Qopt-report:0"
          ;;
   esac
fi
#
# External Libraries Options
#
INC=""
if [ "$WINT" == "Y" ]; then
   case "$COMP" in
      "f95")
          INC="-p$WINTER/lib.abm"
          ;;
      "g95")
          INC="-I$WINTER/lib.g95"
          ;;
      "gfortran")
          INC=""
          ;;
      "ifort")
          if [ "$ARCH" == "m32" ]; then
             INC="-I$WINTER/lib.if8"
          else
             INC="-I$WINTER/lib.i64"
          fi
          ;;
   esac
fi
#
# Changing to the Src Directory
#
cd $CRYSFML/Src
#
# Compilation Process
#
echo " ########################################################"
echo " #### Crystallographic Fortran Modules Library (5.0) ####"
echo " #### JRC - JGP                            1999-2015 ####"
echo " ########################################################"
if [ "$COMP" == "ifort" ]; then
   $COMP $OPT1  CFML_GlobalDeps_Linux_Intel.f90
else
   $COMP $OPT1  CFML_GlobalDeps_Linux.f90
fi
$COMP $OPT1  CFML_Math_Gen.f90
$COMP $OPT1  CFML_LSQ_TypeDef.f90
$COMP $OPT1  CFML_Spher_Harm.f90
$COMP $OPT1  CFML_Random.f90
$COMP $OPT1  CFML_FFTs.f90
if [ "$COMP" == "gfortran" ]; then
   $COMP $OPT1  CFML_String_Util_gf.f90
else
   $COMP $OPT1  CFML_String_Util.f90
fi
if [ "$WINT" == "N" ]; then
   $COMP $OPT1  CFML_IO_Mess.f90       $INC
else
   $COMP $OPT1  CFML_IO_MessWin.f90       $INC
fi
$COMP $OPT1  CFML_Profile_TOF.f90
$COMP $OPT1  CFML_Profile_Finger.f90
$COMP $OPT1  CFML_Profile_Functs.f90
$COMP $OPT1  CFML_Math_3D.f90
$COMP $OPT1  CFML_Optimization.f90
$COMP $OPT1  CFML_LSQ_TypeDef.f90
$COMP $OPT1  CFML_Optimization_LSQ.f90
$COMP $OPT2  CFML_Sym_Table.f90
$COMP $OPT2  CFML_Chem_Scatt.f90
$COMP $OPT2  CFML_BVSpar.f90
$COMP $OPT1  CFML_Diffpatt.f90
$COMP $OPT2  CFML_Bonds_Table.f90
$COMP $OPT1  CFML_Cryst_Types.f90
$COMP $OPT1  CFML_Symmetry.f90
$COMP $OPT1  CFML_ILL_Instrm_Data.f90
$COMP $OPT1  CFML_EoS_Mod.f90
$COMP $OPT1  CFML_Reflct_Util.f90
$COMP $OPT1  CFML_Atom_Mod.f90
$COMP $OPT1  CFML_Geom_Calc.f90
$COMP $OPT1  CFML_Molecules.f90
$COMP $OPT1  CFML_Form_CIF.f90
$COMP $OPT1  CFML_Export_Vtk.f90
$COMP $OPT1  CFML_Sfac.f90
$COMP $OPT1  CFML_Extinction_Correction.f90
$COMP $OPT1  CFML_Propagk.f90
$COMP $OPT1  CFML_Maps.f90
$COMP $OPT1  CFML_SXTAL_Geom.f90
$COMP $OPT1  CFML_Conf_Calc.f90
$COMP $OPT1  CFML_Optimization_SAn.f90 $INC
$COMP $OPT1  CFML_MagSymm.f90
$COMP $OPT1  CFML_Msfac.f90
$COMP $OPT1  CFML_Polar.f90
$COMP $OPT1  CFML_Refcodes.f90
#
# Making CrysFML Library
#
DIRLIB="LibC"
LIBNAME="libcrysfml.a"
if [ "$WINT" == "Y" ]; then
   DIRLIB="LibW"
   LIBNAME="libwcrysfml.a"
fi
ar cr $LIBNAME *.o
mv *.mod $CRYSFML/$IDIR/$DIRLIB
mv *.a $CRYSFML/$IDIR/$DIRLIB
rm *.o
#
# Changing to default directory
#
cd $CRYSFML/Scripts
