#!/bin/sh
# Compilation script for CrysFML library
# Author: Javier Gonzalez-Platas
# Revision: Oct-2008
#
if [ a$1 = a ]
then
cat << !
make_crysfml  : Make the CrysFML Library using Fortran Linux Compilers
Syntax        : make_crysfml af95:g95:gfortran:ifort:lf95 [win] [deb]
!
exit
fi
#
# Compiler Name
#
COMP=$1
if [ $COMP != "lf95" ]
then
   if [ $COMP != "g95" ]
   then
      if [ $COMP != "gfortran" ]
      then
         if [ $COMP != "ifort" ]
         then
            if [ $COMP != "af95" ]
            then
               echo "Compiler Name was wrong!!!"
               exit
            fi
         fi
      fi
   fi
fi
#
# Detect if Directories exists
#
case $COMP
in
   'f95')
       if [ -d "./Absoft" ]
       then
          if [ -d "./Absoft/LibC" ]
          then
             echo " "
          else
             mkdir "./Absoft/LibC"
             mkdir "./Absoft/LibW"
          fi
       else
          mkdir "Absoft"
          mkdir "./Absoft/LibC"
          mkdir "./Absoft/LibW"
       fi
       ;;
   'g95')
       if [ -d "./G95" ]
       then
          if [ -d "./G95/LibC" ]
          then
             echo " "
          else
             mkdir "./G95/LibC"
             mkdir "./G95/LibW"
          fi
       else
          mkdir "G95"
          mkdir "./G95/LibC"
          mkdir "./G95/LibW"
       fi
       ;;
   'gfortran')
       if [ -d "./GFortran" ]
       then
          if [ -d "./GFortran/LibC" ]
          then
             echo " "
          else
             mkdir "./GFortran/LibC"
             mkdir "./GFortran/LibW"
          fi
       else
          mkdir "GFortran"
          mkdir "./GFortran/LibC"
          mkdir "./GFortran/LibW"
       fi
       ;;
   'ifort')
       if [ -d "./Intel" ]
       then
          if [ -d "./Intel/LibC" ]
          then
             echo " "
          else
             mkdir "./Intel/LibC"
             mkdir "./Intel/LibW"
          fi
       else
          mkdir "Intel"
          mkdir "./Intel/LibC"
          mkdir "./Intel/LibW"
       fi
       ;;
   'lf95')
       if [ -d "./Lahey" ]
       then
          if [ -d "./Lahey/LibC" ]
          then
             echo " "
          else
             mkdir "./Lahey/LibC"
             mkdir "./Lahey/LibW"
          fi
       else
          mkdir "Lahey"
          mkdir "./Lahey/LibC"
          mkdir "./Lahey/LibW"
       fi
       ;;
esac
#
# More options
#
MODE=con
DEBUG=nodeb
if [ $# -ge 2 ]
then
   if [ $2 = "win" ]
   then
      MODE=$2
   else
      if [ $2 = "deb" ]
      then
         DEBUG=$2
      fi
   fi
   if [ $# -eq 3 ]
   then
      DEBUG=deb
   fi
fi
#
# Compilation Options
#
if [ $DEBUG = "deb" ]
then
   case $COMP
   in
      'f95')
          OPT1="-c -g -O0"
          OPT2="-c -g -O0"
          ;;
      'g95')
          OPT1="-c -g -Wall"
          OPT2="-c -g -Wall"
          ;;
      'gfortran')
          OPT1="-c -g -Wall"
          OPT2="-c -g -Wall"
          ;;
      'ifort')
          OPT1="-c -g -warn"
          OPT2="-c -g -warn"
          ;;
      'lf95')
          OPT1="-c -g"
          OPT2="-c -g"
          ;;
   esac
else
   case $COMP
   in
      'f95')
          OPT1="-c -O2 -N11"
          OPT2="-c -O0 -N11"
          ;;
      'g95')
          OPT1="-c -O"
          OPT2="-c -O0"
          ;;
      'gfortran')
          OPT1="-c -O"
          OPT2="-c -O0"
          ;;
      'ifort')
          OPT1="-c -O -warn"
          OPT2="-c -O0 -warn"
          ;;
      'lf95')
          OPT1="-c -O --nchk --tpp"
          OPT2="-c -O0 --nchk --tpp"
          ;;
   esac
fi
#
# External Libraries Options
#
if [ $MODE = "con" ]
then
   case $COMP
   in
      'af95')
          INC=""
          ;;
      'g95')
          INC=""
          ;;
      'gfortran')
          INC=""
          ;;
      'ifort')
          INC=""
           ;;
      'lf95')
          INC=""
          ;;
   esac
else
   case $COMP
   in
      'af95')
          INC="-p/Applications/wint/lib.abm"
          ;;
      'g95')
          INC="-I/usr/local/wint/lib.g95"
          ;;
      'gfortran')
          INC=""
          ;;
      'ifort')
          INC="-I/usr/local/wint/lib.if8"
          ;;
      'lf95')
          INC="--include .:/usr/local/wint/lib.l95"
          ;;
   esac
fi
#
# Changing to the Src Directory
#
cd ./Src/CFML
#
# Compilation Process
#
echo " ########################################################"
echo " #### Crystallographic Fortran Modules Library (3.0) ####"
echo " #### JRC - JGP                            1999-2008 ####"
echo " ########################################################"
if [ $COMP = "lf95" ]
then
   $COMP $OPT1  f2kcli.f90
fi
$COMP $OPT1  cfml_math_gen.f90
$COMP $OPT1  cfml_string_util.f90
$COMP $OPT1  cfml_random.f90
$COMP $OPT1  cfml_fft.f90
$COMP $OPT1  cfml_fft_nf.f90
$COMP $OPT1  cfml_profile_tof.f90
$COMP $OPT1  cfml_profile_finger.f90
$COMP $OPT1  cfml_profile_functs.f90
$COMP $OPT1  cfml_optimization.f90
$COMP $OPT1  cfml_optimization_lsq.f90
$COMP $OPT1  cfml_math_3d.f90
$COMP $OPT1  cfml_spher_harm.f90
$COMP $OPT2  cfml_sym_table.f90
$COMP $OPT2  cfml_chem_scatt.f90
$COMP $OPT1  cfml_cryst_types.f90
$COMP $OPT1  cfml_diffpatt.f90
$COMP $OPT2  cfml_bonds_table.f90
$COMP $OPT1  cfml_symmetry.f90
$COMP $OPT1  cfml_reflct_util.f90
$COMP $OPT1  cfml_atom_mod.f90
$COMP $OPT1  cfml_sfac.f90
$COMP $OPT1  cfml_propagk.f90
$COMP $OPT1  cfml_geom_calc.f90
$COMP $OPT1  cfml_maps.f90
$COMP $OPT1  cfml_molecules.f90
$COMP $OPT1  cfml_form_cif.f90
$COMP $OPT1  cfml_conf_calc.f90
$COMP $OPT1  cfml_refcodes.f90
$COMP $OPT1  cfml_polar.f90
$COMP $OPT1  cfml_magsymm.f90
$COMP $OPT1  cfml_msfac.f90
$COMP $OPT1  cfml_ill_instrm_data.f90
$COMP $OPT1  cfml_sxtal_geom.f90
if [ $MODE = "con" ]
then
   $COMP $OPT1  cfml_io_mess.f90       $INC
else
   $COMP $OPT1  cfml_io_messwin.f90       $INC
fi
$COMP $OPT1  cfml_optimization_san.f90 $INC
#
# Making CrysFML Library
#
if [ $MODE = "con" ]
then
   case $COMP
   in
      'af95')
          ar cr libcrysfml.a *.o
          mv *.mod ../../Absoft/LibC
          mv *.a ../../Absoft/LibC
          ;;
      'g95')
          ar cr libcrysfml.a *.o
          mv *.mod ../../G95/LibC
          mv *.a ../../G95/LibC
          ;;
      'gfortran')
          ar cr libcrysfml.a *.o
          mv *.mod ../../GFortran/LibC
          mv *.a ../../GFortran/LibC
          ;;
      'ifort')
          ar cr libcrysfml.a *.o
          mv *.mod ../../Intel/LibC
          mv *.a ../../Intel/LibC
          ;;
      'lf95')
          $COMP *.o --out libcrysfml.a --nshared
          mv *.mod ../../Lahey/LibC
          mv *.a ../../Lahey/LibC
          ;;
   esac
else
   case $COMP
   in
      'af95')
          ar cr libwcrysfml.a *.o
          mv *.mod ../../Absoft/LibW
          mv *.a ../../Absoft/LibW
          ;;
      'g95')
          ar cr libwcrysfml.a *.o
          mv *.mod ../../G95/LibW
          mv *.a ../../G95/LibW
          ;;
      'gfortran')
          ar cr libwcrysfml.a *.o
          mv *.mod ../../GFortran/LibW
          mv *.a ../../GFortran/LibW
          ;;
      'ifort')
          ar cr libwcrysfml.a *.o
          mv *.mod ../../Intel/LibW
          mv *.a ../../Intel/LibW
          ;;
      'lf95')
          $COMP *.o --out libwcrysfml.a --nshared
          mv *.mod ../../Lahey/LibW
          mv *.a ../../Lahey/LibW
          ;;
   esac
fi
rm *.o
#
# Changing to default directory
#
cd ../..
