#!/bin/sh
# Script to compile the Program: Faults
#
if [ a$1 = a ]
then
cat << !
make_faults : Make the Faults Console Program for gfortran/Intel Compilers (MacOS)
Syntax           : make_faults gfortran:ifort [deb]
!
exit
fi
#
# Define Main Directory (defined as environment variables in .bashrc)
#
#CRYSFML=$HOME/CrysFML
#PROGCFML=$HOME/ProgCFML
#
# Faults Directory
#
cd $CRYSFML/Program_Examples/Faults/Src
#
# Compiler Name
#
COMP=$1
if [ $COMP != "ifort" ]
   then
   if [ $COMP != "gfortran" ]
      then
        echo "Compiler Name was wrong!!!"
        cd ..
        exit
    fi
fi
DEBUG=nodeb
if [ $# -eq 2 ]
then
   DEBUG=$2
fi
#
# Compilation Options
#
if [ $DEBUG = "deb" ]
then
   case $COMP
   in
      'gfortran')
          OPT1="-c -g"
            ;;
      'ifort')
          OPT1="-c -g"
            ;;
   esac
else
   case $COMP
   in
      'gfortran')
          OPT1="-c -O3"
            ;;
      'ifort')
          OPT1="-c -O3 -vec-report0"
            ;;
   esac
fi
#
# External Libraries Options
#
case $COMP
in
   'gfortran')
      INC="-I$CRYSFML/gfortran/LibC"
      LIB="-L$CRYSFML/gfortran/LibC"
      LIBSTATIC="-lcrysfml"
      LIBDYNAMIC="-lcrysfml"
     ;;
   'ifort')
      if [ $DEBUG = "deb" ]
      then
         INC="-I$CRYSFML/ifort_debug/LibC"
         LIB="-L$CRYSFML/ifort_debug/LibC"
      else
         INC="-I$CRYSFML/ifort/LibC"
         LIB="-L$CRYSFML/ifort/LibC"
      fi
      LIBDYNAMIC="-lcrysfml"
      LIBSTATIC="-lcrysfml"
     ;;
esac
#
# Compilation Process
#
echo " ########################################################"
echo " #### Faults Console Program                   (1.0) ####"
echo " #### JRC - MCC - MR -JR               CopyLeft-2015 ####"
echo " ########################################################"
$COMP $OPT1 Diffax_glb.f90    $INC
$COMP $OPT1 Faults_Read.f90   $INC
$COMP $OPT1 Diffax_calc.f90   $INC
$COMP $OPT1 Faults.f90        $INC
#
case $COMP
in
  'gfortran')
     #$COMP *.o  -o fp2k $LIB $LIBDYNAMIC
     $COMP *.o  -o Faults -static $LIB $LIBSTATIC
     ;;
  'ifort')
     #$COMP *.o  -o fp2k $LIB $LIBDYNAMIC
     $COMP *.o -o Faults -static-intel $LIB $LIBSTATIC
     ;;
esac
#
# Compress program  !not for MacOS
#
#upx --compress-icons=0 Faults
#
# Purge files
#
rm -rf *.o *.mod
mv -f Faults $PROGCFML/DistFPS/Faults
cp ../Help/Faults_Manual.pdf $PROGCFML/DistFPS/Docs/.
cd $CRYSFML/Program_Examples/Faults/Scripts/MacOS
#
