include(LibFindMacros)

find_path(WINTERACTER_INCLUDE_DIR NAMES winteracter.mod PATHS ENV WINTERACTER)

find_library(WINTERACTER_LIBRARY NAMES winter PATHS ENV WINTERACTER)

set(WINTERACTER_PROCESS_INCLUDES WINTERACTER_INCLUDE_DIR)

set(WINTERACTER_PROCESS_LIBS WINTERACTER_LIBRARY)

libfind_process(WINTERACTER)