include(LibFindMacros)

find_path(CRYSFML_INCLUDE_DIR NAMES cfml_globaldeps.mod PATHS ENV CRYSFML)

find_library(CRYSFML_LIBRARY NAMES crysfml PATHS ENV CRYSFML)

set(CRYSFML_PROCESS_INCLUDES CRYSFML_INCLUDE_DIR)

set(CRYSFML_PROCESS_LIBS CRYSFML_LIBRARY)

libfind_process(CRYSFML)