include(LibFindMacros)

find_path(WCRYSFML_INCLUDE_DIR NAMES cfml_globaldeps.mod PATHS ENV WCRYSFML)

find_library(WCRYSFML_LIBRARY NAMES wcrysfml PATHS ENV WCRYSFML)

set(WCRYSFML_PROCESS_INCLUDES WCRYSFML_INCLUDE_DIR)

set(WCRYSFML_PROCESS_LIBS WCRYSFML_LIBRARY)

libfind_process(WCRYSFML)