#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from runtest_cfml import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()

f.add(from_string = '|Fc|^2      Num',
      num_lines = 10,
      abs_tolerance = 1.0e-6)

if os.name == "nt":
    test.run('calc_powder.exe',['Si_Laue.cfl'], {'powder': f})
else:
    test.run('calc_powder',['Si_Laue.cfl'], {'powder': f})

sys.exit(test.return_code)
