#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from runtest_cfml import Filter, TestRun

test = TestRun(__file__, sys.argv)

f = Filter()

f.add(from_string = 'lambda',
      num_lines = 3,
      abs_tolerance = 1.0e-2)

test.run('calc_powder',['SrTiO3.cfl'], {'dat': f})

sys.exit(test.return_code)
