#!/bin/sh
# Script to compile the Program: cryscalcon
#
if [ a$1 = a ]
then
cat << !
make_cryscalc : Make the cryscalcon Program for Absoft/G95/GFortran/Intel/Lahey Compilers (Linux)
Syntax        : make_cryscalcon af95:g95:ifort:lf95:gfortran
!
exit
fi
#
# Compiler Name
#
COMP=$1
if [ $COMP != "lf95" ]
then
   if [ $COMP != "g95" ]
   then
     if [ $COMP != "gfortran" ]
     then
       if [ $COMP != "ifort" ]
       then
         if [ $COMP != "af95" ]
         then
            echo "Compiler Name was wrong!!!"
            exit
         fi
       fi
     fi
   fi
fi
DEBUG=nodeb
if [ $# -eq 2 ]
then
   DEBUG=$2
fi
#
# Compilation Options
#
if [ $DEBUG = "deb" ]
then
   case $COMP
   in
      'af95')
          OPT1="-c -g -O0"
            ;;
      'g95')
          OPT1="-c -g"
            ;;
      'gfortran')
          OPT1="-c -g"
            ;;
      'ifort')
          OPT1="-c -g"
            ;;
      'lf95')
          OPT1="-c -g"
             ;;
   esac
else
   case $COMP
   in
      'af95')
          OPT1="-c -O2 -N11"
            ;;
      'g95')
          OPT1="-c -O"
            ;;
      'gfortran')
          OPT1="-c -O"
            ;;
      'ifort')
          OPT1="-c -O2 -w -vec-report0"
            ;;
      'lf95')
          OPT1="-c -O --nchk --tpp"
             ;;
   esac
fi
#
# External Libraries Options
#
case $COMP
in
   'af95')
      INC="-I../../Absoft/LibC"
      LIB="-L../../Absoft/LibC"
      LIBSTATIC="-lcrysfml"
      LIBDYNAMIC="-lcrysfml"
     ;;
   'g95')
      INC="-I../../G95/LibC"
      LIB="-L../../G95/LibC"
      LIBSTATIC="-lcrysfml"
      LIBDYNAMIC="-lcrysfml"
      ;;
   'gfortran')
      INC="-I../../GFortran/LibC"
      LIB="-L../../GFortran/LibC"
      LIBSTATIC="-lcrysfml"
      LIBDYNAMIC="-lcrysfml"
     ;;
   'ifort')
      INC="-I../../ifort64/LibC"
      LIB="-L../../ifort64/LibC"
      LIBDYNAMIC="-lcrysfml"
      LIBSTATIC="-lcrysfml"
     ;;
   'lf95')
      INC="--mod .:../../Lahey/LibC"
      LIB="-L../../Lahey/LibC"
      LIBDYNAMIC="-lcrysfml"
      LIBSTATIC="-lcrysfml -lpthread"
     ;;
esac
#
# Compilation Process
#
$COMP $OPT1 menu_0.f90    $INC
$COMP $OPT1 menu_1.f90    $INC
$COMP $OPT1 menu_2.f90    $INC
$COMP $OPT1 menu_3.f90    $INC
$COMP $OPT1 menu_4.f90    $INC
$COMP $OPT1 menu_5.f90    $INC
$COMP $OPT1 calsym.f90    $INC
case $COMP
in
  'af95')
     $COMP *.o  -o cryscalcon -static $LIB $LIBSTATIC
     ;;
  'g95')
     $COMP *.o  -o cryscalcon  $LIB $LIBSTATIC
     ;;
  'gfortran')
     $COMP *.o  -o cryscalcon  $LIB $LIBSTATIC
     ;;
  'ifort')
     $COMP *.o -o cryscalcon -static-intel $LIB $LIBSTATIC
     ;;
  'lf95')
     $COMP *.o --out cryscalcon --staticlink $LIB $LIBDYNAMIC
     ;;
esac
rm -rf *.o *.mod
upx --compress-icons=0 cryscalcon
mv -f cryscalcon $PROGCFML/DistFPS/cryscalcon
