FROM ci_crysfml_xenial_ifort

SHELL ["/bin/bash", "-c"]

ARG CI_COMMIT_SHORT_SHA
ARG CI_COMMIT_REF_NAME

ENV CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA}
ENV CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME}
ENV HDF5_INCLUDE_PATH=/hdf5/include

COPY ./ /app/
WORKDIR /app

CMD BuildServer/Unix/build.sh ifort && cp -a build_ifort /artifacts/