FROM ubuntu:xenial

ENV https_proxy http://proxy.ill.fr:8888
ENV http_proxy http://proxy.ill.fr:8888

RUN apt-get update
RUN apt-get install -y cmake
RUN apt-get install -y g++
RUN apt-get install -y git
RUN apt-get install -y libhdf5-dev
RUN apt-get install -y libboost-all-dev

RUN git clone https://github.com/nexusformat/code.git
RUN mkdir code/build; cd code/build; cmake ..; cmake --build .; make install
RUN rm -rf code

RUN git clone https://github.com/blosc/c-blosc.git
RUN mkdir c-blosc/build; cd c-blosc/build; cmake ..; cmake --build .; make install
RUN rm -rf c-blosc

ENV PATH=/opt/intel/bin:$PATH