FROM ci_crysfml_xenial_ifort

SHELL ["/bin/bash", "-c"]

ARG CI_COMMIT_SHORT_SHA
ARG CI_COMMIT_REF_NAME

ENV CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA}
ENV CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME}
ENV HDF5_INCLUDE_PATH=/hdf5/include
ENV HDF5_LIBRARY_PATH=/hdf5/lib
ENV PYTHON_LIBRARY_PATH=/fullprof/libpython3.7m.so

COPY ./ /app/
WORKDIR /app

CMD BuildServer/Unix/build_release.sh ifort && cp -a ifort /artifacts/