FROM ci_crysfml_xenial_gfortran_08

SHELL ["/bin/bash", "-c"]

ARG CI_COMMIT_SHORT_SHA
ARG CI_COMMIT_REF_NAME

ENV CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA}
ENV CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME}

COPY ./ /app/
WORKDIR /app

CMD BuildServer/Unix/build08.sh gfortran && cp -a build_gfortran_08 /artifacts/