#! /bin/sh
# Compilation for CrysFML + CrysFGL libraries
# Author: Javier Gonzalez-Platas
# Date: Dic-2008
#
if [ a$1 = a ]
then
cat << !
makecrys  : Make the Libraries CrysFML (Console , Winteracter) and CrysFGL using Fortran Mac Compilers
Syntax    : makecrys_mac [af95:g95:gfortran:ifort:lf95] [all]
!
exit
fi
#
# Compiler Name
#
COMP=$1
if [ $COMP != "lf95" ]
then
   if [ $COMP != "g95" ]
   then
      if [ $COMP != "gfortran" ]
      then
         if [ $COMP != "ifort" ]
         then
            if [ $COMP != "af95" ]
            then
               echo "Compiler Name was wrong!!!"
               exit
            fi
         fi
      fi
   fi
fi
#
# Console version
#
./Scripts/MacOS/make_crysfml $1
#
# Winteracter version
#
if [ $2 = "all" ]
then
   ./Scripts/MacOS/make_crysfml $1 win
   ./Scripts/MacOS/make_crysfgl $1
fi   
