#! /bin/sh
# Compilation for CrysFML + CrysFGL libraries
# Author: Javier Gonzalez-Platas
# Revision: Oct-2008
#
if [ a$1 = a ]
then
cat << !
make_lib  : Make the Libraries CrysFML (Console , Winteracter) and CrysFGL using Fortran Linux Compilers
Syntax    : make_lib af95:g95:gfortran:ifort:lf95
!
exit
fi
#
# Compiler Name
#
COMP=$1
if [ $COMP != "lf95" ]
then
   if [ $COMP != "g95" ]
   then
      if [ $COMP != "gfortran" ]
      then
         if [ $COMP != "ifort" ]
         then
            if [ $COMP != "af95" ]
            then
               echo "Compiler Name was wrong!!!"
               exit
            fi
         fi
      fi
   fi
fi
#
# Load the Sources
#
./Scripts/Linux/load_crysfml
#
# Console version
#
./Scripts/Linux/make_crysfml $1
#
# Winteracter version
#
./Scripts/Linux/make_crysfml $1 win
./Scripts/Linux/make_crysfgl $1
