# Try to find by casual method if include path or library path (or both) is not defined
if(NOT HDF5_INCLUDE_PATH OR NOT HDF5_LIBRARY_PATH)
    find_package(HDF5)
endif()

# Override include path if user defined it
if(HDF5_INCLUDE_PATH)
    set(HDF5_INCLUDE_DIR ${HDF5_INCLUDE_PATH})
    message(STATUS "Using ${HDF5_INCLUDE_PATH} as HDF5 headers (provided by user)")
endif()

# Override library path if user defined it
if(HDF5_LIBRARY_PATH)
    message(STATUS "Try to find HDF5 libraries in ${HDF5_LIBRARY_PATH} (provided by user)")
	if(APPLE)
	    set(LIBS1 hdf5 hdf5_fortran)
	    set(LIBS2 m dl sz z)
	elseif(UNIX)
	    set(LIBS1 hdf5 hdf5_fortran)
	    set(LIBS2 m dl sz z pthread)
	elseif(WIN32 OR MSYS)
        get_filename_component(COMPILER_NAME ${CMAKE_Fortran_COMPILER} NAME_WE)
        if(COMPILER_NAME STREQUAL ifort)
	         set(LIBS1 hdf5 hdf5_fortran hdf5_f90cstub szip zlib)
	         message(STATUS "User will need to add in path: hdf5.dll hdf5_f90cstub.dll hdf5_fortran.dll")
        else()
	        set(LIBS1 libhdf5 libhdf5_fortran libhdf5_f90cstub libszip libz)
	        message(STATUS "User will need to add in path: libgcc_s_seh-1.dll libgfortran-5.dll libhdf5_f90cstub-0.dll libhdf5_fortran-0.dll libhdf5-0.dll libquadmath-0.dll libszip.dll libwinpthread-1.dll zlib1.dll")
	    endif()
	else()
	    message(FATAL ERROR "OS unknown")
	endif()
	
	set(HDF5_LIBRARIES)
    foreach(libname ${LIBS1})
        set(temp_lib temp_lib-NOTFOUND)
        find_library(temp_lib NAMES ${libname} PATHS ${HDF5_LIBRARY_PATH} NO_DEFAULT_PATH)
        if(${temp_lib} STREQUAL temp_lib-NOTFOUND)
	        message(FATAL_ERROR "${libname} not found")
	    else()
	        list(APPEND HDF5_LIBRARIES ${temp_lib})
	    endif()
    endforeach()
    foreach(libname ${LIBS2})
        set(temp_lib temp_lib-NOTFOUND)
        find_library(temp_lib NAMES ${libname} PATHS ${HDF5_LIBRARY_PATH})
        if(${temp_lib} STREQUAL temp_lib-NOTFOUND)
	        message(FATAL_ERROR "${libname} not found")
	    else()
	        list(APPEND HDF5_LIBRARIES ${temp_lib})
	    endif()
    endforeach()

endif()

message(STATUS Found HDF5_LIBRARIES:${HDF5_LIBRARIES})
