C -------------------------------------------------------------
	SUBROUTINE WRITE_HEADER(IFILE)
	CHARACTER*24 TDATE
	CHARACTER*27  TEXT
	INCLUDE 'FILES.INC'
	INCLUDE 'FLAGS.INC'
C
C HEADER
1	FORMAT(1X,76('*')/2(' *',74(' '),'*'/),
     1  ' *',24X,'    ABSORB PROGRAM       ',24X,' *'/
     1 2(' *',74(' '),'*'/),
     2  ' *',24X,'   BASE VERSION',F5.2,'     ',25X,'*'/
     2  ' *',24X,A27,23X,'*'/
     2  ' *',20X,'LATEST UPDATE:   ',a12,25X,'*'/	
     2  2(' *',74(' '),'*'/),1X,76('*'))

C WRITE HEADER TO PRINT FILE
	WRITE(IFILE,2)
2	FORMAT(//////////////////)
	IF(ICONFIG .EQ. 1)THEN	
		TEXT='VERSION FOR STOE & cie GmbH'			! STOE
	ELSE	
		TEXT='               '
	ENDIF
	
	WRITE(IFILE,1)version_no,TEXT,version_date
	CALL FDATE(TDATE)      
	WRITE(IFILE,40)TDATE,FNAME(1)(1:ILEN(1))
40	FORMAT(/10X,'ABSORB RUN ON: ',A24/10X,'EXPERIMENT FILE IS: ',A/)

C


	RETURN
	END
C
C
	SUBROUTINE WRITE_CRYSTAL_DATA(IUNIT)
C
C WRITES SUMMARY OF CRYSTAL MODELK TO UNIT IUNIT
C ASSUMES IUNIT WILL UNDERSTAND FORTRAN CARRIAGE CONTROL
C
	include 'Crystalmodel.inc'
	include 'DAC.inc'
	include 'Unitcell.inc'
	INCLUDE 'Chemistry.inc'
	INCLUDE 'FLAGS.INC'
C
	CHARACTER*25 STARS
	CHARACTER*1 XYZ(3),SIGN
	DATA XYZ/'X','Y','Z'/	
C
	STARS='*************************'
	RAD=ATAN(1.0)/45.0
	VOLAM=(XLAMB/CVOL)**2
C
c NOTE: THE FACE EQUATIONS AND CORNERS ARE PRINTED AS GENERATED
C SO AS TO AID IN FINDING PROBLEMS WITH THE MODEL SETUP

C
C STUFF ABOUT INPUT DATA
C

	WRITE(IUNIT,300)STARS,STARS
300	FORMAT(/A25,'******* INPUT DATA *******',A25/)     

	WRITE(IUNIT,310)XLAMB
310	FORMAT(5X,'WAVELENGTH = ',F8.5,' A'/)

C
C  ADD OUTPUT OF UB IF PRESENT
C
	IF(IUB .EQ. 3)THEN
		WRITE(IUNIT,249)
249		FORMAT(5X,'CARTESIAN AXES SPECIFIED FOR INPUT',
	1				' ORIENTATION MATRIX WERE:')
		DO I=1,3
			SIGN='+'
			IF(IBL(I) .LT. 0)SIGN='-'
			J=IABS(IBL(I))
			WRITE(IUNIT,248)XYZ(I),SIGN,XYZ(J)
248			FORMAT(5X,'+',A1,' IS PARALLEL TO ',A1,A1,' OF BUSING-LEVY')
		ENDDO
C
		WRITE(IUNIT,251)
251		FORMAT(/5X,'ORIENTATION MATRIX ON BUSING-LEVY AXES IS: ')
		DO I=1,3
			WRITE(IUNIT,252)(UB(I,J),J=1,3)
252			FORMAT(5X,3F10.6)
		ENDDO
		WRITE(IUNIT,253)AUB
253		FORMAT(/5X,'  UNIT CELL FROM UB: ',3F10.5/
	1            5X,'                     ',3F10.5,'  VOL = ',F10.4)
	ENDIF
C
	IF(ICELL .EQ. 1)THEN
		WRITE(IUNIT,254)ACELL
254		FORMAT(/5X,'UNIT CELL FROM FILE: ',3F10.5/
	1            5X,'                     ',3F10.5,'  VOL = ',F10.4)
	ENDIF
	WRITE(IUNIT,255)CVOL
255	FORMAT(5X,'CELL VOLUME USED IN PROGRAM = ',F10.3,' A^3')
C
C
C *************************************************************
C
	WRITE(IUNIT,222)STARS,STARS
222	FORMAT(//A25,'**** DATA CORRECTIONS ****',A25/)
C
 	IF(IABSCO .EQ. 0)THEN
		WRITE(IUNIT,114)
114		FORMAT(5X,'NO CRYSTAL ABSORPTION WILL BE CALCULATED'//)
C
	ELSE 
		IF (ICHEM .EQ. 1)THEN
		  WRITE(IUNIT,225)
225		  FORMAT(5X,'ABSORPTION COEFFICIENT CALCULATED FROM FORMULA:')
		  DO I=1,92
				IF(NE(I) .GT. 0.)THEN
					WRITE(IUNIT,223)ELEMENTSTRING(2*I-1:2*I),NE(I)
223					FORMAT(10X,A2,F8.2)
				ENDIF
	   	  ENDDO
		  WRITE(IUNIT,230)NINT(Z),DENSITY
230		  FORMAT(17X,'WITH Z =',I3/5X,'CALCULATED DENSITY = ',F8.3)
		ENDIF
		WRITE(IUNIT,115)ABSCO*1000.
115		FORMAT (5X,'LINEAR ABSORPTION COEFFICIENT = ',F7.2,' MM-1'//)
	ENDIF
C
C HERE REPORT CRYSTAL THE MODEL
C
	IPT=NPT(1)*NPT(2)*NPT(3)
	IVOL=NINT(XVOL)
	IF(IMODELFORM .EQ. 5)THEN
C FILLED GASKET
	IGASKETVOL=NINT(3.14159*RGASKET*RGASKET*TG)
	WRITE(IUNIT,800)NPT,IPT,IVOL,IGASKETVOL
800	FORMAT(//5X,'CRYSTAL ABSORPTION MODEL BASED ON FILLED GASKET'//
     1  5X,'GAUSSIAN GRID SET FOR CRYSTAL OF ',
     1  I2,' x ',I2,' x ',I2,' POINTS'/
     2  5X,I5,' TOTAL GRID POINTS: CRYSTAL FILLING GASKET HOLE'/
     3  5X,'CALCULATED CRYSTAL VOLUME = ',I10,' CUBIC MICRONS'/
     4  5X,'CALCULATED GASKET VOLUME  = ',I10,' CUBIC MICRONS'/)
			
	ELSE IF(IMODELFORM .EQ. 4)THEN
C SPHERE
	VEST=4./3.*3.14159*XTAL_RAD**3.
	IPT=NINT(NPT(1)**3.)
	WRITE(IUNIT,810)XTAL_RAD,XTAL_RAD*ABSCO,NPT(1),NPT(1),NPT(1),
	1				IPT,IVOL,VEST
810	FORMAT(//5X,'CRYSTAL ABSORPTION MODEL IS A SPHERE'//
	1  5X,'GAUSSIAN GRID SET FOR SPHERICAL CRYSTAL OF RADIUS ',
	1  F6.2,' MICRONS AND MU*R = ',F6.3/
     1  5X,I2,' x ',I2,' x ',I2,' POINTS= ',I5,' TOTAL GRID POINTS'/
     3  5X,'CALCULATED CRYSTAL VOLUME = ',I10,' CUBIC MICRONS'/
     4  5X,'         ACTUAL VOLUME IS = ',F12.1,' CUBIC MICRONS')
C
	IF(IMODELORIGIN .EQ. 1)THEN
		WRITE(IUNIT,201)MODEL_ORIGIN
201		FORMAT(5X,'NOTE THAT ORIGIN SHIFTED AT USER REQUEST BY ',3F12.2)
	ENDIF		


	ELSE IF(IMODELFORM .EQ. 0)THEN
	WRITE(IUNIT,840)
840	FORMAT(//5X,'NO CRYSTAL MODEL')

	ELSEIF(ISMALL .EQ. 1)THEN
	WRITE(IUNIT,850)
850	FORMAT(//5X,'CRYSTAL ABSORPTION MADE ASSUMING SMALL BEAM IN A ',
	1			'RELATIVELY BIG CRYSTAL IN DAC')



	ELSE
C  NORMAL
	WRITE(IUNIT,820)NPT,IPT,IVOL
820	FORMAT(//5X,'CRYSTAL ABSORPTION MODEL BASED ON USER DESCRIPTION'//
     1  5X,'GAUSSIAN GRID SET FOR CRYSTAL OF ',
     1  I2,' x ',I2,' x ',I2,' POINTS'/
     2  5X,I5,' TOTAL GRID POINTS'/
     3  5X,'CALCULATED CRYSTAL VOLUME = ',I10,' CUBIC MICRONS')
C

	ENDIF

C
C
	IF(IDAC .EQ. 0)THEN
	  WRITE(IUNIT,140)
140	  FORMAT(//5X,'NO DIAMOND-ANVIL CELL CORRECTIONS')
	ELSE
	  WRITE(IUNIT,150)IDAC,PSIMAX(1)/rad,PSIMAX(2)/rad
150	  FORMAT(//,5X,'DATA CORRECTED FOR DIAMOND-ANVIL CELL',
     1    ' TYPE ',I3,':'/5X,'PSIMAX(IBEAM ANVIL) = ',
     2    F5.1,10X,'  PSIMAX(DBEAM ANVIL) = ',F5.1)
c

C DAC CRYSTAL INFO
		IF(IXANVIL .NE. 0)THEN
			WRITE(IUNIT,830)TCRYSTAL
830			FORMAT(//5X,'CRYSTAL THICKNESS GIVEN AS ',F5.1' MICRONS')
			IF(IXANVIL .EQ. 1)THEN
				WRITE(IUNIT,831)
831				FORMAT(5X,'LYING ON INCIDENT-BEAM ANVIL')
			ELSE
				WRITE(IUNIT,832)
832				FORMAT(5X,'LYING ON DIFFRACTED-BEAM ANVIL')
			ENDIF
		ENDIF
C
C  ROTATION OF CELL
	  IF(ABS(PHIZERO) .LT. 0.1)THEN
		WRITE(IUNIT,142)
142		FORMAT(/5X,'DAC SET FACE-ON TO BEAM WHEN ANGLES ARE ZERO'//)
	  ELSEIF(PHIZERO .LT. 0.1)THEN
		WRITE(IUNIT,143)ABS(PHIZERO)
143		FORMAT(/5X,'DAC ROTATED ',F7.2,' DEGREES ANTI-CLOCKWISE ',
	1	'(VIEWED FROM ABOVE) FROM FACE-ON TO BEAM WHEN ANGLES ARE ZERO'//)
	  ELSE
		WRITE(IUNIT,144)PHIZERO
144		FORMAT(/5X,'DAC ROTATED ',F7.2,' DEGREES CLOCKWISE ',
	1	'(VIEWED FROM ABOVE) FROM FACE-ON TO BEAM WHEN ANGLES ARE ZERO'//)
	  ENDIF
C
C CELL DESCRIPTION
	  IF(IDAC .LE. 4)THEN
		DO I=1,2	
		WRITE(IUNIT,151)I,TDIAMOND(I),MU_DIA(I)
151		FORMAT('     THICKNESS OF DIAMOND ANVIL ',I1,': ',F6.3,
	1				' MM, MU = ',F7.4,' MM-1')
		WRITE(IUNIT,156)I,TBERYL(I),MU_BE(I)
156		FORMAT('           THICKNESS OF PLATTEN ',I1,': ',F6.3,
	1			' MM, MU = ',F7.4,' MM-1')
		ENDDO
	  ELSE
		IF(NTERMS_PSI .LT. 0)THEN
			WRITE(IUNIT,157)ABSPSI_PAR(1),ABSPSI_PAR(2)
157			FORMAT('     USER-SUPPLIED DAC TRANSMISSION FUNCTION',
	1		' WITH SUM(ABSCO*T) FOR ANVIL 1:',F7.3,'  ANVIL 2:',F7.3)
		ELSE
			WRITE(IUNIT,158)
158			FORMAT('     USER-SUPPLIED DAC TRANSMISSION FUNCTION',
	1		' VIA A TABLE OF VALUES')
		ENDIF
	  ENDIF
C
C   OUTPUT FOR SHADOWING
	  IF(ISHAD .EQ. 1)THEN
		WRITE(IUNIT,170)TG,RGASKET
170		FORMAT(/5x,'GASKET SHADOWING CORRECTIONS WILL BE MADE: '//
     1	  5X,'GASKET THICKNESS = ',F5.1,
     2	     ' MICRONS, RADIUS = ',F5.1,' MICRONS')

		IF(IOPAQUE .EQ. 0)THEN
		  IF(GASKETMU .GT. 99.)THEN
			WRITE(IUNIT,172)GASKETMU*1000.
172			FORMAT(5X,'GASKET ABSORPTION COEFF = ',F12.0,' MM-1')
		  ELSE
			WRITE(IUNIT,171)GASKETMU*1000.
171			FORMAT(5X,'GASKET ABSORPTION COEFF = ',F9.2,' MM-1')
		  ENDIF
		ELSE
		  WRITE(IUNIT,174)
174		  FORMAT(5X,'GASKET ASSUMED TOTALLY OPAQUE')
		ENDIF			
		WRITE(IUNIT,173)THRESHO
173		FORMAT(5X,'REFLECTION WILL BE CONSIDERED TOTALLY OBSCURED IF '
     2    ,'FRACTION CRYSTAL ILLUMINATED IS LESS THAN ',F4.2/)
C
C
	    IF(IMODELFORM .EQ. 5)THEN
			WRITE(IUNIT,180)
180			FORMAT(5X,'CRYSTAL FILLS THE GASKET HOLE'//)
		ELSE
			IF(IMEDIA .EQ. 1)THEN
				WRITE(IUNIT,181)MU_MEDIA*1000.
181				FORMAT(5X,'ABSORPTION COEFF OF PRESSURE MEDIUM = ',
	1					F6.2,' MM-1')
			ELSE
				WRITE(IUNIT,182)
182				FORMAT(5X,'NON-ABSORBING PRESSURE MEDIUM ')
			ENDIF
		ENDIF	 							
	  ELSE
165		WRITE(IUNIT,175)
175		FORMAT(/5X,'NO GASKET SHADOWING CORRECTIONS WILL BE MADE'//)
	  ENDIF
	ENDIF
C
C  REPORT SPECIALS
C
	IF(ICONFIG .NE. 0)CALL WRITE_CRYSTAL_SPECIAL

C
C REPORT DATA RESTRICTIONS/MODIFICATIONS
	WRITE(IUNIT,600)STARS(1:20),STARS(1:20),FACT
600	FORMAT(//A20,' DATA RESTRICTIONS/MODIFICATIONS ',A20//
     25X,'A REFL. WILL BE A LESS-THAN IF I< ',F3.1,' SIGMA I'/)
C
C HANDLING OF NEGATIVE INTENSITIES AND SIGMAS
C
	IF(INEGINT .EQ. 1)THEN
		WRITE(IUNIT,610)
610		FORMAT(5X,'REFLECTIONS WITH NEGATIVE INTENSITIES',
	1				' WILL BE PROCESSED AND OUTPUT')
	ELSEIF(INEGINT .EQ. 0)THEN
		WRITE(IUNIT,612)
612		FORMAT(5X,'REFLECTIONS WITH NEGATIVE INTENSITIES',
	1				' WILL BE RETAINED BUT SET TO ZERO')
     	ELSEIF(INEGINT .EQ. -1)THEN
		WRITE(IUNIT,614)
614		FORMAT(5X,'REFLECTIONS WITH NEGATIVE INTENSITIES',
	1				' WILL NOT BE OUTPUT')
	ENDIF
C
C HANDLING OF NEGATIVE SIGMAS(!)
	IF(INEGSIG .EQ. 1)THEN
		WRITE(IUNIT,616)
616		FORMAT(5X,'REFLECTIONS WITH NEGATIVE SIG(FSQ)',
	1				' WILL BE RETAINED AND PROCESSED')
     	ELSEIF(INEGSIG .EQ. -1)THEN
		WRITE(IUNIT,618)
618		FORMAT(5X,'REFLECTIONS WITH NEGATIVE SIG(FSQ)',
	1				' WILL NOT BE OUTPUT')
	ENDIF


   

C 2THETA LIMITS
C
	IF(TTHMIN .GT. 0.)THEN
	WRITE(IUNIT,120)TTHMIN
120	FORMAT(/5X,'DATA WITH 2THETA < ',F8.3,
	1					' DEGREES WILL BE EXCLUDED')
	ENDIF
	IF(TTHMAX .LT. 180.)THEN
	WRITE(IUNIT,121)TTHMAX
121	FORMAT(/5X,'DATA WITH 2THETA > ',F8.3,
	1					' DEGREES WILL BE EXCLUDED')
	ENDIF

C RESCALING

	IF(ABS(SCALE_I - 1.0) .GT. 0.0001)THEN
		WRITE(IUNIT,135)SCALE_I
135	FORMAT(/5X,'INTENSITIES WILL BE MULTIPLIED BY ',F9.4,' ON INPUT')
	ENDIF
C
C LP WARNING
	WRITE(IUNIT,29)
29	FORMAT(/5X,'NO MONOCHROMATOR OR LP CORRECTIONS MADE') 





	RETURN
	END 